# Construção de grafos

Código irá construir todos os grafos de N vértices e seu número cromático

In [ ]:
!pip install networkx[default]

In [1]:
from pathlib import Path
import networkx as nx
import itertools
import random
import time
random.seed(time.time())

In [2]:
def gen_edges(n):
    return itertools.chain.from_iterable(
        itertools.combinations(itertools.combinations(range(n), 2), i)
        for i in range(n+1))

In [3]:
def graphs(n):
    for edges in gen_edges(n):
        g = nx.Graph()
        g.add_nodes_from(range(n))
        g.add_edges_from(edges)
        yield g


In [4]:
def chrome(g):
    return len(set(nx.coloring.greedy_color(g).values()))

In [5]:

def write_graph(g, file_name):
    print('TYPE : TSP',
          f'DIMENSION: {g.number_of_nodes()}',
          'EDGE_DATA_FORMAT: EDGE_LIST',
          'EDGE_WEIGHT_TYPE: EXPLICIT',
          'EDGE_WEIGHT_FORMAT: FULL_MATRIX',
          'EDGE_DATA_SECTION',
          sep='\n',
          file=file_name)
    for e in g.edges():
        print(*e, file=file_name)
    print(-1, file=file_name)
    print('EDGE_WEIGHT_SECTION',
          file=file_name)
    for i in range(g.number_of_nodes()):
        print(*([0.0]*g.number_of_nodes()),
              sep='\t', file=file_name)
    print('DIFF_EDGE',
          '0 0',
          'CHROM_NUMBER',
          chrome(g),
          'EOF',
          sep='\n',
          file=file_name)

In [6]:
def write_file_graph(g, file_name):
    with open(file_name, "w") as file:
        file.write(f"TYPE : TSP\nDIMENSION: {g.number_of_nodes()}\nEDGE_DATA_FORMAT: EDGE_LIST\nEDGE_WEIGHT_TYPE: EXPLICIT\nEDGE_WEIGHT_FORMAT: FULL_MATRIX\nEDGE_DATA_SECTION\n")
        for e in g.edges():
            file.write(f"{e[0]} {e[1]}\n")
        file.write("-1\n")
        file.write(f"EDGE_WEIGHT_SECTION\n")
    
        for row in nx.adjacency_matrix(g).toarray().tolist():
            file.write(f"{row}\n")
    
        file.write(f"'DIFF_EDGE'\n0 0\nCHROM_NUMBER\n{chrome(g)}\nEOF")

    # print(f"Arquivo {file_name} criado com sucesso")

Qantidade N de Vértices a serem considerados

In [7]:
N = 7 # quantidade de vertices

qtd_training = 582 # quantidade de amostras para treinamento
qtd_testing = 180 # quantidade de amostras para teste

# referencia para os arquivos dos dados de cada grafo 
# salvando em um diretorio
file_name_origin = "m10.graph"
dir_training_name = f"qrnn-training-{N}"
dir_testing_name = f"qrnn-testing-{N}"

Construção dos grafos

In [8]:
import numpy as np

In [9]:
def create_graph(input, file_name):
    array = np.random.randint(2, size=(input,input))
    G = nx.from_numpy_array(array)
    # print(G.edges(data=True))
    # print(chrome(G))
    write_file_graph(G, file_name)

In [10]:
value = 762


In [11]:
import os

numbers = [4,5,6,7]

for number in numbers:
    dir_name = f"qrnn-{number}"
    if not os.path.exists(dir_name):
        os.mkdir(dir_name)
    for i in range(value):
        i_padded = str(i).zfill(3)
        create_graph(number, os.path.join(dir_name, f"m{i_padded}.graph"))
    print(f"Arquivos {dir_name}\t criados com sucesso !!!")

Arquivos qrnn-4	 criados com sucesso !!!
Arquivos qrnn-5	 criados com sucesso !!!
Arquivos qrnn-6	 criados com sucesso !!!
Arquivos qrnn-7	 criados com sucesso !!!


In [39]:
import networkx as nx
import numpy as np

# Crie um grafo simples para demonstração
G = nx.Graph()
G.add_edges_from([(1, 2), (2, 3), (3, 1)])

# Obtenha a matriz de adjacência
adj_matrix = nx.adjacency_matrix(G)

# Converta a matriz de adjacência em uma lista de listas ou um array NumPy
adj_matrix_array = adj_matrix.toarray()
print("Matriz de Adjacência:")
print(adj_matrix_array)

# Se preferir, você pode mostrar como uma lista de listas
adj_matrix_list = adj_matrix.toarray().tolist()
print("\nMatriz de Adjacência como Lista de Listas:")
for row in adj_matrix_list:
    print(row)

Matriz de Adjacência:
[[0 1 1]
 [1 0 1]
 [1 1 0]]

Matriz de Adjacência como Lista de Listas:
[0, 1, 1]
[1, 0, 1]
[1, 1, 0]
